language: node_js

node_js: lts/*

cache: npm

before_install:
  - npm i hexo-cli gulp-cli -g

install: npm i

script:
  - hexo clean
  - hexo g
  - gulp

# after_script:
#   - cd ./public
#   - git init
#   - git config user.name "iissnan"
#   - git config user.email "email_address"
#   - git add .
#   - git commit -m "Update docs"
#   - git push -f "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - blog-source

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN # Set in the settings page of your repository, as a secure variable
  on:
    branch: blog-source
  local_dir: public
  target_branch: master
